# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

image: vultkayn/bta-web-app:latest

stages:
  - build
  - test
  - deploy

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - server/node_modules/
    - client/node_modules/

build-server:
  stage: build
  script:
    - cd server/
    - npm install
    - cd ../

lint-server:
  stage: build
  script:
    - cd server/
    - npx eslint .
    - cd ../

build-client:
  stage: build
  script:
    - cd client/
    - npm install
    - npm run build
    - cd ../

lint-client:
  stage: build
  script:
    - cd client/
    - npx eslint .
    - cd ../

test-api-login:
  stage: test
  script:
    - cd server/
    - npm run test login.test.js
    - cd ../
  environment: test

test-client:
  stage: test
  script:
    - cd client/
    - npm run test
    - cd ../
  environment: test

deploy:
  stage: deploy
  script:
    - cd server/
    - npm run deploy
  environment: production
