POST http://127.0.0.1:8888/api/auth/login/
content-type: application/json

{
"univID": "priourb",
"password": "January01!"
}

### 

POST  http://127.0.0.1:8888/api/auth/
content-type: application/json

{
"univID": "priourb",
"password": "January01!",
"firstName": "benjamin",
"lastName": "priour",
"promo": 2024,
"email": "benpr@liu.se"
}

###

POST http://127.0.0.1:8888/api/auth/login/
content-type: application/json

{
    "univID": "priourb",
    "password": "January01!"
}